### ISSUE TITLE
Build failure with GHC 7.10

### ISSUE THREAD

**Issue by ethercrow** [coreyoconnor/vty#65] opened 2015-01-01 12:03 UTC
```
 ~/src/vty % cabal --version
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library
 
 ~/src/vty % ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.0.20141222

 ~/src/vty % cabal build
Building vty-5.2.6...
Preprocessing library vty-5.2.6...
[21 of 33] Compiling Graphics.Vty.PictureToSpans ( src/Graphics/Vty/PictureToSpans.hs, dist/build/Graphics/Vty/PictureToSpans.o )
<command line>: can't load .so/.DLL for: libtinfo.so (libtinfo.so: cannot open shared object file: No such file or directory)
```

**Comment by coreyoconnor** [comment] 2015-01-02 01:07
Thanks!
I don't have a 7.10 environment yet. I'll try installing vty once I do. I don't have a system that uses libtinfo. AFAICT libtinfo.so is a alias for ncurses?

* https://aur.archlinux.org/packages/libtinfo/

Looks like a template haskell environment issue.

Template haskell cannot find the .so for this library. Typically this occurs if the `--extra-lib-dirs` does not contain libtinfo.so (or libncurses.so in my case).

What are the configure options and where is libtinfo.so location? EG: shared/static?

**Comment by ethercrow** [comment] 2015-01-29 19:53
I've managed to install vty on that machine (gentoo without libtinfo.so) after cloning terminfo, running autoreconf and cabal-installing it. I'm not sure what's the root cause, maybe a hackage version of terminfo has configure script expecting libtinfo.so to be available.

**Comment by coreyoconnor** [comment] 2015-08-08 23:55
Closing in favor of #82.
This is another  "bug" caused by requiring a native terminfo library. Too bad I didn't keep a list of all the pain points in setting up build environments properly because of this. haha. There are a lot.

**Closed by coreyoconnor** 2015-08-08 23:55 UTC

**Comment by shanemikel** [comment] 2015-12-26 20:21
I'm having this problem on OpenSUSE.  On some forum I read that curses split into two libraries, and a recommendation to symlink libtinfo to libncurses, but I can't do that.  I'd love to see this fixed, as I'm interested in trying http://yi-editor.github.io/

**Comment by coreyoconnor** [comment] 2015-12-27 00:42
As stated previously: this is an issue with terminfo library. Not vty. Please file an issue with that project.

**Comment by shanemikel** [comment] 2015-12-27 00:49
I'm not complaining, I'm voting for moving over to the terminfo-hs library... actually I guess that comment belonged in #82

**Comment by coreyoconnor** [comment] 2015-12-27 00:52
Ah! My apologies. Yes: definitely vote for #82. :)

**Comment by JonnyRa** [comment] 2026-05-03 20:21
I ran into this on ubuntu 25.10 and found I needed to `apt install libncurses-dev`... hopefully useful if someone else hits the same thing and goes digging through these issue pages.

I was trying to build a brick app which needs vty.  The actual fix was suggested on the comments in a stackoverflow page!
